#!/bin/bash
cd $HOME/crime-time
git pull
if [ $? == 0 ]; then
	unity-editor
else
	output=$(zenity --error --text="Git pull returned an error. Probably a merge conflict" --title="Pull Error" --width=350 --height=150 --extra-button="Fix")
	if [ $output == Fix ]; then
		aaa=$(zenity --file-selection)
		geany $aaa
	fi
fi
